    export const Colors = {
  light: {
    background:       '#F8F6F0',
    card:             '#FFFFFF',
    primary:          '#2D5A8E',
    primaryLight:     '#EBF2FB',
    accent:           '#C8861A',
    text:             '#1A1A1A',
    textSecondary:    '#666666',
    textMuted:        '#999999',
    border:           '#E5E0D8',
    separator:        '#F0ECE4',
    otColor:          '#2D5A8E',
    ntColor:          '#7B3F8C',
    otBg:             '#EBF2FB',
    ntBg:             '#F5EDF9',
    verseHighlight:   '#FFF8E7',
    bookmarkColor:    '#C8861A',
    favoriteColor:    '#E53935',
    tabBar:           '#FFFFFF',
    tabBarActive:     '#2D5A8E',
    tabBarInactive:   '#9E9E9E',
    headerBg:         '#2D5A8E',
    headerText:       '#FFFFFF',
    searchBg:         '#F0ECE4',
    shadowColor:      '#000000',
  },
  dark: {
    background:       '#0F1923',
    card:             '#1C2B3A',
    primary:          '#5B9BD5',
    primaryLight:     '#1A2E42',
    accent:           '#E8A84C',
    text:             '#F0EDE8',
    textSecondary:    '#A0ADB8',
    textMuted:        '#607080',
    border:           '#2A3F55',
    separator:        '#162030',
    otColor:          '#5B9BD5',
    ntColor:          '#B07DC8',
    otBg:             '#1A2E42',
    ntBg:             '#2A1E38',
    verseHighlight:   '#1E2E1A',
    bookmarkColor:    '#E8A84C',
    favoriteColor:    '#EF5350',
    tabBar:           '#1C2B3A',
    tabBarActive:     '#5B9BD5',
    tabBarInactive:   '#607080',
    headerBg:         '#1C2B3A',
    headerText:       '#F0EDE8',
    searchBg:         '#0F1923',
    shadowColor:      '#000000',
  },
};

export type ColorScheme = typeof Colors.light;